<a href="https://colab.research.google.com/github/2303A51434/Applications-of-Data-Mining/blob/main/ADM_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
df=pd.read_csv('/content/heart (2).csv')

In [62]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [64]:
df.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [65]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [66]:
df2=pd.read_csv('/content/titanic (1).csv')
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [67]:
df2.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [68]:
df2['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

888NaN

In [69]:
df2['Age'].mean()

29.69911764705882

In [18]:
df2['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [19]:
df2['Age'].median()

28.0

In [21]:
df2['Age'].fillna(df2['Age'].mean(),inplace=True)

In [27]:
df2['Age'].fillna(df2['Age'].mode(),inplace=True)

In [28]:
df2['Age'].fillna(df2['Age'].median(),inplace=True)

In [29]:
df2['Age'].isna().sum()

0

In [25]:
df2['Fare']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [43]:
df2['Fare'].mean()

32.204207968574636

In [44]:
df2['Fare'].median()

14.4542

In [45]:
df2['Fare'].mode()

0    8.05
Name: Fare, dtype: float64

In [46]:
df2['Fare'].fillna(df2['Cabin'].mean())

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [39]:
df2['Fare'].fillna(df2['Fare'].median())

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
886   NaN
887   NaN
888   NaN
889   NaN
890   NaN
Name: Cabin, Length: 891, dtype: float64

In [48]:
df2['Fare'].fillna(df2['Fare'].mode())

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [49]:
df2['Fare'].isna().sum()

0

In [50]:
df2['Fare'].max()

512.3292

In [51]:
df2['Fare'].min()

0.0

minmax

In [55]:
df2['Fare']=(df2['Fare']-df2['Fare'].min())//(df2['Fare'].max()-df2['Fare'].min())

In [56]:
df2['Fare']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
886    0.0
887    0.0
888    0.0
889    0.0
890    0.0
Name: Fare, Length: 891, dtype: float64

In [58]:
df2['Fare'].unique()

array([0., 1.])

In [59]:
df2['Fare'].value_counts()

Fare
0.0    888
1.0      3
Name: count, dtype: int64

In [70]:
scaler = StandardScaler()

In [71]:
scaler.fit(df2[['Fare']])

StandardScaler()

In [81]:
scaled_data = scaler.transform(df2[['Fare']])
scaled_data

array([[-5.02445171e-01],
       [ 7.86845294e-01],
       [-4.88854258e-01],
       [ 4.20730236e-01],
       [-4.86337422e-01],
       [-4.78116429e-01],
       [ 3.95813561e-01],
       [-2.24083121e-01],
       [-4.24256141e-01],
       [-4.29555021e-02],
       [-3.12172378e-01],
       [-1.13845709e-01],
       [-4.86337422e-01],
       [-1.87093118e-02],
       [-4.90279793e-01],
       [-3.26266659e-01],
       [-6.19988892e-02],
       [-3.86670720e-01],
       [-2.85997284e-01],
       [-5.02948539e-01],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-4.86756223e-01],
       [ 6.63597416e-02],
       [-2.24083121e-01],
       [-1.64441595e-02],
       [-5.02948539e-01],
       [ 4.64700108e+00],
       [-4.89776426e-01],
       [-4.89442190e-01],
       [-9.02720170e-02],
       [ 2.30172882e+00],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 1.00606170e+00],
       [ 3.98582080e-01],
       [-5.02863973e-01],
       [-4.86337422e-01],
       [-2.85997284e-01],
       [-4.22073541e-01],
       [-4.57645492e-01],
       [-2.25593223e-01],
       [-4.89442190e-01],
       [ 1.88762532e-01],
       [-4.89776426e-01],
       [-4.86337422e-01],
       [-3.36334002e-01],
       [-4.92377828e-01],
       [-2.11917743e-01],
       [-2.90024222e-01],
       [ 1.50673744e-01],
       [-4.91371093e-01],
       [ 8.96496787e-01],
       [-1.24919787e-01],
       [ 5.99510151e-01],
       [ 6.63597416e-02],
       [-4.37007438e-01],
       [-5.02863973e-01],
       [-8.96840841e-02],
       [ 2.95895176e-01],
       [-5.02863973e-01],
       [ 9.62353321e-01],
       [ 1.03232136e+00],
       [-8.66638810e-02],
       [-9.02720170e-02],
       [-3.41452240e-01],
       [-4.37007438e-01],
       [-4.84156835e-01],
       [-4.88854258e-01],
       [-4.74004926e-01],
       [-4.37007438e-01],
       [ 2.95895176e-01],
       [ 8.31477855e-01],
       [-3.57390858e-01],
       [ 4.89103607e-01],
       [-4.94391297e-01],
       [-4.89442190e-01],
       [-4.86337422e-01],
       [-6.45157251e-02],
       [-3.97241431e-01],
       [-4.67209469e-01],
       [-4.57142125e-01],
       [-4.91622777e-01],
       [ 2.99922113e-01],
       [-4.37007438e-01],
       [-3.29286862e-01],
       [ 4.37082185e-02],
       [-4.86337422e-01],
       [ 4.64700108e+00],
       [-4.86337422e-01],
       [-4.86337422e-01],
       [-4.90279793e-01],
       [ 5.83317835e-01],
       [-2.34150465e-01],
       [-5.02445171e-01],
       [-4.86337422e-01],
       [ 4.93298232e-02],
       [ 6.27277898e-01],
       [-1.85323848e-01],
       [-1.24919787e-01],
       [-4.89442190e-01],
       [-4.89442190e-01],
       [ 9.07737982e-01],
       [-4.74172044e-01],
       [-4.88854258e-01],
       [-4.89442190e-01],
       [-4.94391297e-01],
       [-4.91874461e-01],
       [-4.89442190e-01],
       [-1.62168958e-01],
       [ 3.98582080e-01],
       [-3.57390858e-01],
       [-4.86337422e-01],
       [-4.50598352e-01],
       [-3.57308306e-01],
       [-4.88854258e-01],
       [-4.92377828e-01],
       [-2.25593223e-01],
       [ 4.33533223e+00],
       [-1.87093118e-02],
       [ 8.31477855e-01],
       [-4.86337422e-01],
       [-4.29555021e-02],
       [-3.86670720e-01],
       [ 9.07737982e-01],
       [-4.22073541e-01],
       [-4.92377828e-01],
       [-5.04625758e-01],
       [-1.98244277e-01],
       [-5.07982210e-01],
       [-4.89442190e-01],
       [-5.06472109e-01],
       [-3.56468689e-01],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-3.45479177e-01],
       [-1.19215630e-01],
       [ 4.20730236e-01],
       [-4.62846282e-01],
       [ 9.46245572e-01],
       [-3.41452240e-01],
       [-4.92377828e-01],
       [-3.29286862e-01],
       [-5.12512515e-01],
       [-4.16872751e-01],
       [ 9.15281006e-02],
       [-4.91455659e-01],
       [ 4.37082185e-02],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-3.96234697e-01],
       [ 6.92548513e-01],
       [-4.86337422e-01],
       [-3.56468689e-01],
       [-5.01186753e-01],
       [ 5.87429338e-01],
       [-4.92714077e-01],
       [-4.86337422e-01],
       [-4.74004926e-01],
       [ 7.51945840e-01],
       [-3.24253190e-01],
       [-3.31300330e-01],
       [-4.91874461e-01],
       [-4.74004926e-01],
       [ 1.50673744e-01],
       [-2.35157199e-01],
       [ 4.58986142e-01],
       [-8.66638810e-02],
       [-1.26429888e-01],
       [ 4.89103607e-01],
       [ 2.60903672e-02],
       [-6.19988892e-02],
       [-4.24256141e-01],
       [-4.88854258e-01],
       [-3.03713226e-02],
       [-4.90279793e-01],
       [-1.35657615e-01],
       [-7.03044477e-02],
       [-3.86670720e-01],
       [-6.48421654e-01],
       [ 7.51945840e-01],
       [-3.45394611e-01],
       [-1.64441595e-02],
       [ 1.36831147e-01],
       [-2.04955168e-01],
       [ 3.58312706e-01],
       [-3.36334002e-01],
       [-1.13845709e-01],
       [-3.36334002e-01],
       [-4.89442190e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-9.02720170e-02],
       [ 2.30172882e+00],
       [-4.92377828e-01],
       [-4.79205715e-01],
       [-4.92377828e-01],
       [-3.86670720e-01],
       [-4.57142125e-01],
       [ 7.51945840e-01],
       [-5.17630753e-01],
       [-5.02948539e-01],
       [-4.86337422e-01],
       [-4.37762489e-01],
       [-3.29286862e-01],
       [-2.70141218e-01],
       [-4.92377828e-01],
       [-2.42463508e-02],
       [-5.06472109e-01],
       [-2.25593223e-01],
       [-5.02445171e-01],
       [-3.86670720e-01],
       [-4.92377828e-01],
       [ 1.63233504e+00],
       [-4.88854258e-01],
       [-1.04785100e-01],
       [ 8.87687861e-01],
       [-4.37007438e-01],
       [-4.86337422e-01],
       [-3.86670720e-01],
       [-4.86337422e-01],
       [-4.89442190e-01],
       [ 1.16370019e+00],
       [-4.60162328e-01],
       [-4.37007438e-01],
       [-5.02445171e-01],
       [-3.86670720e-01],
       [-1.35657615e-01],
       [ 1.03232136e+00],
       [-4.91874461e-01],
       [-3.76603377e-01],
       [-1.64441595e-02],
       [-4.37007438e-01],
       [-4.96404765e-01],
       [-1.24919787e-01],
       [-1.19886115e-01],
       [-4.37007438e-01],
       [-4.01268368e-01],
       [-3.57390858e-01],
       [-3.36334002e-01],
       [-4.37007438e-01],
       [-5.04962007e-01],
       [-5.02948539e-01],
       [ 1.16370019e+00],
       [-4.91874461e-01],
       [-3.56468689e-01],
       [ 4.09740724e-01],
       [-1.24919787e-01],
       [-5.02445171e-01],
       [-4.37762489e-01],
       [-1.13845709e-01],
       [-3.24253190e-01],
       [-2.41449289e-01],
       [-3.41452240e-01],
       [ 9.46245572e-01],
       [ 1.09322879e+00],
       [ 9.66716653e+00],
       [-1.24919787e-01],
       [-4.92377828e-01],
       [-1.64441595e-02],
       [ 9.55306181e-01],
       [-6.48421654e-01],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 1.50673744e-01],
       [-4.91874461e-01],
       [ 2.44149778e+00],
       [ 2.08251241e+00],
       [-2.42463508e-02],
       [-6.48421654e-01],
       [-2.55795253e-01],
       [-5.04214441e-02],
       [-4.92377828e-01],
       [ 9.21244331e-01],
       [-4.92377828e-01],
       [-6.48421654e-01],
       [-6.19988892e-02],
       [-2.40694238e-01],
       [-4.92377828e-01],
       [-4.90279793e-01],
       [-4.57142125e-01],
       [-4.86337422e-01],
       [-1.24919787e-01],
       [-4.74004926e-01],
       [-4.57142125e-01],
       [-4.89442190e-01],
       [-3.86670720e-01],
       [-4.92377828e-01],
       [ 9.39198431e-01],
       [ 1.18542955e+00],
       [-3.89187556e-01],
       [-4.70229672e-01],
       [-4.89442190e-01],
       [-9.02720170e-02],
       [-5.02863973e-01],
       [ 2.40299019e+00],
       [-3.43136943e-02],
       [ 4.33533223e+00],
       [-4.92377828e-01],
       [-1.80290176e-01],
       [-6.48421654e-01],
       [-3.99758267e-01],
       [-4.86337422e-01],
       [ 2.40299019e+00],
       [ 1.58417891e+00],
       [ 1.54424578e+00],
       [-1.65189161e-01],
       [ 4.97829980e-01],
       [ 1.02594470e+00],
       [ 4.63441690e+00],
       [-1.24919787e-01],
       [-4.89442190e-01],
       [-1.19886115e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-3.66536033e-01],
       [ 2.67111778e+00],
       [ 2.05969377e+00],
       [-5.02445171e-01],
       [-4.89442190e-01],
       [-3.99758267e-01],
       [-6.45157251e-02],
       [ 7.51945840e-01],
       [ 2.08251241e+00],
       [-5.22831542e-01],
       [-3.86670720e-01],
       [-2.35157199e-01],
       [ 5.18971402e-01],
       [-1.80290176e-01],
       [-7.45830687e-02],
       [ 2.44149778e+00],
       [-2.85997284e-01],
       [ 2.04257929e+00],
       [-4.89442190e-01],
       [ 6.92548513e-01],
       [ 2.05969377e+00],
       [-4.86337422e-01],
       [ 6.63597416e-02],
       [-1.24919787e-01],
       [ 4.64700108e+00],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.24253190e-01],
       [-3.28280127e-01],
       [-4.74004926e-01],
       [-4.62679164e-01],
       [ 5.62923980e-02],
       [-5.02863973e-01],
       [-2.90024222e-01],
       [-5.02948539e-01],
       [-4.57142125e-01],
       [ 4.58986142e-01],
       [-3.86670720e-01],
       [-4.89776426e-01],
       [-4.89776426e-01],
       [-8.66638810e-02],
       [-9.02720170e-02],
       [-3.57390858e-01],
       [-5.06472109e-01],
       [-3.36334002e-01],
       [-5.02445171e-01],
       [ 8.66713557e-01],
       [-5.02863973e-01],
       [-4.92377828e-01],
       [ 7.46912168e-01],
       [ 4.67879633e-01],
       [-5.17630753e-01],
       [-4.86337422e-01],
       [ 2.08251241e+00],
       [-2.24083121e-01],
       [ 1.00606170e+00],
       [-5.02445171e-01],
       [ 3.61006469e+00],
       [-5.67631221e-01],
       [-4.91874461e-01],
       [ 3.93272305e+00],
       [-3.31467448e-01],
       [-4.88854258e-01],
       [ 3.98582080e-01],
       [-4.89442190e-01],
       [ 8.31477855e-01],
       [ 2.95895176e-01],
       [-3.86670720e-01],
       [-4.92796629e-01],
       [-4.06805407e-01],
       [ 1.76774081e+00],
       [-4.91455659e-01],
       [-4.88854258e-01],
       [ 1.63233504e+00],
       [-3.12172378e-01],
       [-4.91455659e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-4.37007438e-01],
       [-3.93717861e-01],
       [-4.88854258e-01],
       [-4.86337422e-01],
       [-4.50598352e-01],
       [-3.29286862e-01],
       [-4.74004926e-01],
       [-2.25593223e-01],
       [-4.92377828e-01],
       [-2.70896269e-01],
       [-4.91874461e-01],
       [-1.35657615e-01],
       [-4.89442190e-01],
       [-5.10331928e-01],
       [ 1.16370019e+00],
       [-6.48421654e-01],
       [-4.88854258e-01],
       [-4.86337422e-01],
       [ 5.95568003e-03],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-1.62168958e-01],
       [-4.89442190e-01],
       [-4.92714077e-01],
       [-4.89860992e-01],
       [-3.58482158e-01],
       [-2.41449289e-01],
       [-5.02445171e-01],
       [-1.24919787e-01],
       [-1.24919787e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [-1.13845709e-01],
       [-3.24253190e-01],
       [-1.24919787e-01],
       [-5.04962007e-01],
       [ 4.77107360e-01],
       [ 1.76774081e+00],
       [ 4.37082185e-02],
       [-2.70896269e-01],
       [ 4.64700108e+00],
       [-4.37007438e-01],
       [-1.19886115e-01],
       [-4.57142125e-01],
       [-4.91874461e-01],
       [-3.86670720e-01],
       [-4.85079004e-01],
       [ 9.99769611e-01],
       [-2.55795253e-01],
       [-1.13845709e-01],
       [-2.60661807e-01],
       [-3.43136943e-02],
       [-8.96840841e-02],
       [-2.46398395e-01],
       [-8.96840841e-02],
       [ 1.14566354e+00],
       [-4.86337422e-01],
       [-4.89442190e-01],
       [-1.13845709e-01],
       [ 3.95813561e-01],
       [-4.37007438e-01],
       [-4.92377828e-01],
       [-1.13845709e-01],
       [-4.86337422e-01],
       [ 1.26763803e-01],
       [-3.86670720e-01],
       [-4.86337422e-01],
       [-5.06472109e-01],
       [-6.48421654e-01],
       [-1.13845709e-01],
       [-4.92881195e-01],
       [-2.60661807e-01],
       [-5.02445171e-01],
       [-4.74004926e-01],
       [-8.96840841e-02],
       [-3.70730088e-01],
       [-4.50346668e-01],
       [ 3.98582080e-01],
       [-2.25593223e-01],
       [-5.06556675e-01],
       [-4.96992698e-01],
       [-4.01016685e-01],
       [ 2.95895176e-01],
       [-6.48421654e-01],
       [-4.86337422e-01],
       [-4.55380340e-01],
       [ 1.18542955e+00],
       [-1.35657615e-01],
       [ 1.16370019e+00],
       [-5.04214441e-02],
       [-4.86337422e-01],
       [-3.28280127e-01],
       [-2.46398395e-01],
       [-5.02445171e-01],
       [-3.43136943e-02],
       [ 3.48329928e-01],
       [-4.86337422e-01],
       [-3.57308306e-01],
       [ 9.27453868e-01],
       [-3.44387877e-01],
       [ 2.40299019e+00],
       [-4.91455659e-01],
       [-4.74004926e-01],
       [-4.92377828e-01],
       [-4.94810098e-01],
       [-4.55380340e-01],
       [ 1.09322879e+00],
       [ 1.54424578e+00],
       [-1.24919787e-01],
       [-1.13845709e-01],
       [-1.94887825e-01],
       [ 4.89103607e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [-1.19131064e-01],
       [ 5.47578765e-01],
       [-4.97496065e-01],
       [ 3.65765123e-02],
       [-4.37007438e-01],
       [-1.62168958e-01],
       [-1.24919787e-01],
       [-4.89442190e-01],
       [ 1.23417160e+00],
       [-4.89442190e-01],
       [-5.02948539e-01],
       [ 5.18971402e-01],
       [-5.02863973e-01],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 3.81703316e+00],
       [-4.88854258e-01],
       [-4.16872751e-01],
       [-1.24919787e-01],
       [-5.02863973e-01],
       [-5.02863973e-01],
       [-1.98244277e-01],
       [-4.74004926e-01],
       [-1.19886115e-01],
       [-1.13845709e-01],
       [ 1.49441243e+00],
       [-3.56468689e-01],
       [ 3.48245362e-01],
       [ 7.81141137e-01],
       [-1.87093118e-02],
       [-1.87093118e-02],
       [-1.24919787e-01],
       [ 1.49441243e+00],
       [-1.24919787e-01],
       [-1.24919787e-01],
       [-3.69304552e-01],
       [-2.35157199e-01],
       [ 9.15281006e-02],
       [ 1.58417891e+00],
       [-1.24919787e-01],
       [-4.90783161e-01],
       [-5.02948539e-01],
       [-4.91874461e-01],
       [-1.13845709e-01],
       [ 1.48911959e-01],
       [ 3.93272305e+00],
       [ 9.55306181e-01],
       [-2.98078096e-01],
       [-4.92377828e-01],
       [-4.89442190e-01],
       [-3.76603377e-01],
       [-4.86337422e-01],
       [-4.86337422e-01],
       [-1.62168958e-01],
       [-4.89442190e-01],
       [-2.24083121e-01],
       [-5.02863973e-01],
       [-4.90279793e-01],
       [-4.37007438e-01],
       [ 3.88095935e-01],
       [-1.17117595e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [-3.56468689e-01],
       [-3.86670720e-01],
       [ 4.77107360e-01],
       [-3.57308306e-01],
       [-4.88854258e-01],
       [-4.43810379e-02],
       [ 1.58417891e+00],
       [-1.24919787e-01],
       [ 1.59482670e-01],
       [-4.72998191e-01],
       [ 9.55306181e-01],
       [-3.46401346e-01],
       [ 9.46245572e-01],
       [-4.86337422e-01],
       [-4.86337422e-01],
       [-5.04962007e-01],
       [ 9.27453868e-01],
       [-5.02445171e-01],
       [-4.92377828e-01],
       [-1.24919787e-01],
       [-1.62168958e-01],
       [ 1.60230236e-02],
       [-6.48421654e-01],
       [-5.02948539e-01],
       [ 4.97829980e-01],
       [-1.04785100e-01],
       [-4.89442190e-01],
       [ 2.05289083e-01],
       [-4.86337422e-01],
       [-1.13845709e-01],
       [-3.35327268e-01],
       [-4.89442190e-01],
       [-3.43136943e-02],
       [ 1.88762532e-01],
       [ 2.44149778e+00],
       [-1.87093118e-02],
       [-5.06472109e-01],
       [-3.36334002e-01],
       [-4.92377828e-01],
       [-4.86337422e-01],
       [ 6.60333014e-01],
       [-3.58482158e-01],
       [-3.24253190e-01],
       [ 1.36831147e-01],
       [-4.37007438e-01],
       [-3.57390858e-01],
       [ 4.09740724e-01],
       [-3.31467448e-01],
       [-4.90279793e-01],
       [-3.24253190e-01],
       [ 2.34754408e-03],
       [-3.99758267e-01],
       [ 9.21244331e-01],
       [-4.89442190e-01],
       [-4.92714077e-01],
       [-4.43810379e-02],
       [-5.06387543e-01],
       [-3.43136943e-02],
       [-6.48421654e-01],
       [-8.66638810e-02],
       [-3.86670720e-01],
       [-4.88854258e-01],
       [-1.19886115e-01],
       [ 1.50673744e-01],
       [-3.24253190e-01],
       [-4.90279793e-01],
       [ 7.46912168e-01],
       [-8.66638810e-02],
       [ 4.89103607e-01],
       [-2.60661807e-01],
       [ 8.96496787e-01],
       [-4.89442190e-01],
       [ 6.63597416e-02],
       [-4.96404765e-01],
       [-4.96404765e-01],
       [-4.89442190e-01],
       [-1.85323848e-01],
       [-4.78619796e-01],
       [-4.90783161e-01],
       [-5.12512515e-01],
       [ 8.31477855e-01],
       [-4.89442190e-01],
       [-3.36334002e-01],
       [-3.86670720e-01],
       [ 1.63233504e+00],
       [ 2.04257929e+00],
       [-5.02948539e-01],
       [-1.33225345e-01],
       [-4.97496065e-01],
       [-4.88854258e-01],
       [ 8.31477855e-01],
       [-3.86670720e-01],
       [-4.91874461e-01],
       [-4.86337422e-01],
       [ 3.98582080e-01],
       [ 1.36831147e-01],
       [ 3.98582080e-01],
       [-4.37007438e-01],
       [-3.86670720e-01],
       [-6.48421654e-01],
       [-4.91874461e-01],
       [-4.86337422e-01],
       [-4.50262103e-01],
       [ 2.95895176e-01],
       [ 9.66716653e+00],
       [-4.84575637e-01],
       [ 8.96496787e-01],
       [-4.62679164e-01],
       [ 2.95895176e-01],
       [ 1.36831147e-01],
       [ 1.88762532e-01],
       [ 1.50673744e-01],
       [-4.43635777e-01],
       [-4.91455659e-01],
       [ 3.60679280e+00],
       [ 4.99255516e-01],
       [-3.78280596e-01],
       [ 4.89103607e-01],
       [-5.02948539e-01],
       [-1.13845709e-01],
       [-3.76603377e-01],
       [-4.86337422e-01],
       [-4.92714077e-01],
       [ 1.58417891e+00],
       [-4.94391297e-01],
       [ 3.93272305e+00],
       [-1.19131064e-01],
       [-3.57390858e-01],
       [-4.92544946e-01],
       [-4.90279793e-01],
       [-1.24919787e-01],
       [-3.76603377e-01],
       [-1.19131064e-01],
       [ 2.40299019e+00],
       [-3.41452240e-01],
       [ 3.48329928e-01],
       [-1.13845709e-01],
       [ 3.98582080e-01],
       [-4.57478375e-01],
       [-3.86670720e-01],
       [-4.94391297e-01],
       [ 3.93272305e+00],
       [-4.37007438e-01],
       [-3.36334002e-01],
       [-4.91874461e-01],
       [ 1.60230236e-02],
       [-5.06387543e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [ 4.20730236e-01],
       [-4.74004926e-01],
       [-2.25593223e-01],
       [-4.92629511e-01],
       [-1.24919787e-01],
       [-4.88854258e-01],
       [ 3.60679280e+00],
       [-2.70141218e-01],
       [-6.48421654e-01],
       [-3.86670720e-01],
       [-3.86670720e-01],
       [-3.24253190e-01],
       [ 4.37082185e-02],
       [ 9.66716653e+00],
       [-4.89442190e-01],
       [-4.89442190e-01],
       [-4.43810379e-02],
       [ 9.39198431e-01],
       [ 4.63441690e+00],
       [-3.24253190e-01],
       [-4.88854258e-01],
       [ 7.81141137e-01],
       [-2.40694238e-01],
       [-3.86670720e-01],
       [ 4.20730236e-01],
       [-4.92377828e-01],
       [-1.85323848e-01],
       [-3.97241431e-01],
       [-4.57142125e-01],
       [-4.89442190e-01],
       [ 6.60333014e-01],
       [-3.56468689e-01],
       [-4.91455659e-01],
       [-4.16872751e-01],
       [-4.86337422e-01],
       [ 1.09322879e+00],
       [-3.56468689e-01],
       [-5.04962007e-01],
       [-5.02863973e-01],
       [ 1.76774081e+00],
       [-4.91874461e-01],
       [ 9.21244331e-01],
       [ 1.48911959e-01],
       [-4.92377828e-01],
       [-1.62168958e-01],